# -*- coding: utf-8 -*-
"""2461800_DiptiGiri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODVYZDIeR4v8PiH8myJmf7HIJwanYmBc

#5CS037 – Assignment I: Statistical Interpretation & EDA
# Original Notebook Code (Problem 1A – Problem 3)
# Dataset: Human_Development_Index_Dataset.csv
# Author: Dipti Giri
"""

# -----------------------------
# Common Imports
# -----------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sns.set(style="whitegrid")


# -----------------------------
# Load Dataset
# -----------------------------
# Load CSV with encoding fix (handles UnicodeDecodeError)
try:
   df = pd.read_csv("Human_Development_Index_Dataset.csv", encoding="utf-8")
except UnicodeDecodeError:
  df = pd.read_csv("Human_Development_Index_Dataset.csv", encoding="latin1")


# Basic inspection
print(df.shape)
df.head()

"""# Problem 1A – Single Year HDI Exploration (2022)"""

# Task 1: Extract Latest Year (2022)
years = df['year'].unique()
print("Available years:", sorted(years))


hdi_2022_df = df[df['year'] == 2022].copy()
print(hdi_2022_df.shape)

# Task 2: Data Exploration
hdi_2022_df.head(10)


print("Rows, Columns:", hdi_2022_df.shape)
print("\nColumn info:")
print(hdi_2022_df.dtypes)

# Task 3: Missing Values & Cleaning
print("\nMissing values per column:")
print(hdi_2022_df.isna().sum())


# Replace special characters representing missing values
hdi_2022_df.replace("–", np.nan, inplace=True)


# Convert numeric columns safely
numeric_cols = ['hdi', 'life expectancy', 'gross inc percap', 'gender development']
for col in numeric_cols:
  if col in hdi_2022_df.columns:
   hdi_2022_df[col] = pd.to_numeric(hdi_2022_df[col], errors='coerce')


# Remove duplicates
hdi_2022_df.drop_duplicates(inplace=True)


# Handle missing values (drop rows with missing HDI)
hdi_2022_df = hdi_2022_df.dropna(subset=['hdi'])

# Task 4: Basic Statistics
mean_hdi = hdi_2022_df['hdi'].mean()
median_hdi = hdi_2022_df['hdi'].median()
std_hdi = hdi_2022_df['hdi'].std()


print("Mean HDI:", mean_hdi)
print("Median HDI:", median_hdi)
print("Std HDI:", std_hdi)


highest_hdi_country = hdi_2022_df.loc[hdi_2022_df['hdi'].idxmax(), 'country']
lowest_hdi_country = hdi_2022_df.loc[hdi_2022_df['hdi'].idxmin(), 'country']


print("Highest HDI:", highest_hdi_country)
print("Lowest HDI:", lowest_hdi_country)

# Task 5: Filtering and Sorting
# Some datasets use slightly different column names for GNI
print("Available columns:", hdi_2022_df.columns)


# Find correct GNI column name safely
gni_col = None
for col in hdi_2022_df.columns:
  if 'gross' in col.lower() and 'inc' in col.lower():
   gni_col = col
   break


print("Using GNI column:", gni_col)


high_hdi = hdi_2022_df[hdi_2022_df['hdi'] > 0.800]
high_hdi_sorted = high_hdi.sort_values(by=gni_col, ascending=False)


high_hdi_sorted.head(10)

# Task 6: HDI Category Column


def classify_hdi(hdi_value: float) -> str:
    """
    Classify a country into UNDP HDI categories based on 2022 HDI value.
    """
    if pd.isna(hdi_value):
        return np.nan
    if hdi_value < 0.550:
        return "Low"
    elif 0.550 <= hdi_value <= 0.699:
        return "Medium"
    elif 0.700 <= hdi_value <= 0.799:
        return "High"
    else:  # hdi_value >= 0.800
        return "Very"

hdi_2022_df["HDI_Category"] = hdi_2022_df["hdi"].apply(classify_hdi)

# Verification 1: show category counts
print("HDI_Category counts:")
display(hdi_2022_df["HDI_Category"].value_counts(dropna=False))

# Verification 2: check boundary values are classified correctly
boundary_check = hdi_2022_df[
    (hdi_2022_df["hdi"].between(0.545, 0.555)) |
    (hdi_2022_df["hdi"].between(0.695, 0.705)) |
    (hdi_2022_df["hdi"].between(0.795, 0.805))
].copy()

print("Boundary classification check (values near 0.550, 0.700, 0.800):")
display(boundary_check[["country", "hdi", "HDI_Category"]].sort_values("hdi"))

# Verification 3: confirm new column exists in dataframe
print("New column added?", "HDI_Category" in hdi_2022_df.columns)

# Save final dataframe
hdi_2022_df.to_csv("HDI_category_added.csv", index=False)
print("Saved file: HDI_category_added.csv")

"""#Problem 1B – HDI Visualization & Trend Analysis (2020–2022)"""

# -----------------------------
# Task 1: Data Extraction and Saving
# -----------------------------
# Filter dataset for years 2020, 2021, and 2022
hdi_problem1B_df = df[df["year"].isin([2020, 2021, 2022])].copy()

# Intermediate verification output
print("Filtered years present in the dataset:")
print(sorted(hdi_problem1B_df["year"].unique()))

print("Shape of filtered dataset (2020–2022):", hdi_problem1B_df.shape)
display(hdi_problem1B_df.head())

# Save the filtered dataset
hdi_problem1B_df.to_csv("HDI_problem1B.csv", index=False)
print("Saved file: HDI_problem1B.csv")

# Task 2: Data Cleaning (STEP-BY-STEP OUTPUT)
# -----------------------------
# Convert numeric columns safely
numeric_cols = ['hdi', 'year', 'gross inc percap', 'life expectancy', 'gender development']
for col in numeric_cols:
  if col in hdi_1b.columns:
   hdi_1b[col] = pd.to_numeric(hdi_1b[col], errors='coerce')


print("Missing values after conversion:\n")
print(hdi_1b[['hdi','year']].isna().sum())


# Drop rows with missing essential values
before_rows = hdi_1b.shape[0]
hdi_1b.dropna(subset=['hdi', 'country', 'year'], inplace=True)
after_rows = hdi_1b.shape[0]


print(f"Rows before cleaning: {before_rows}")
print(f"Rows after cleaning: {after_rows}")


# Remove duplicates
hdi_1b.drop_duplicates(inplace=True)


# Standardize country names
hdi_1b['country'] = hdi_1b['country'].str.strip()


print("Task 2 Output: Cleaned Data Preview")
hdi_1b[['country','year','hdi']].head(10)
# Save cleaned dataset
hdi_1b.to_csv("HDI_problem1B.csv", index=False)
print("File saved: HDI_problem1B.csv")

# -----------------------------
# Task 3: Visualizations (CLEAR & EXAM-FRIENDLY)
# -----------------------------


# Task 3A: Line Chart – HDI Trend (Country-Level)
selected_countries = ['Nepal', 'India', 'China', 'United States', 'Germany']
line_df = hdi_1b[hdi_1b['country'].isin(selected_countries)]


plt.figure(figsize=(9,5))
for c in selected_countries:
  temp = line_df[line_df['country'] == c]
  plt.plot(temp['year'], temp['hdi'], marker='o', linewidth=2, label=c)


plt.xlabel("Year")
plt.ylabel("HDI")
plt.title("HDI Trends for Selected Countries (2020–2022)")
plt.legend(title="Country")
plt.grid(True)
plt.show()

# Task 3B: Bar Chart – Average HDI by Region
region_avg = hdi_1b.groupby(['region', 'year'])['hdi'].mean().reset_index()


plt.figure(figsize=(10,5))
sns.barplot(data=region_avg, x='region', y='hdi', hue='year')
plt.xticks(rotation=45)
plt.xlabel("Region")
plt.ylabel("Average HDI")
plt.title("Average HDI by Region (2020–2022)")
plt.legend(title="Year")
plt.show()

# Task 3C: Box Plot – HDI Distribution by Year
plt.figure(figsize=(7,5))
sns.boxplot(data=hdi_1b, x='year', y='hdi')
plt.xlabel("Year")
plt.ylabel("HDI")
plt.title("HDI Distribution Across Years")
plt.show()

# Task 3D: Scatter Plot – HDI vs GNI per Capita
# Detect correct GNI column dynamically
gni_col = None
for col in hdi_1b.columns:
  if 'gross' in col.lower() and 'inc' in col.lower():
      gni_col = col
      break


if gni_col:
  plt.figure(figsize=(7,5))
  sns.regplot(data=hdi_1b, x=gni_col, y='hdi', scatter_kws={'alpha':0.4})
  plt.xlabel("GNI per Capita")
  plt.ylabel("HDI")
  plt.title("Relationship between GNI per Capita and HDI (2020–2022)")
  plt.show()
else:
  print("GNI per Capita variable not available in the dataset.")

#Task4- Short Analysis Questions:
#compute HDI change(2020-2022)
# Pivot data to compare HDI across years
hdi_wide = (
    hdi_problem1B_df
    .pivot_table(index="country", columns="year", values="hdi", aggfunc="mean")
)

# Keep only countries with values in both 2020 and 2022
hdi_wide = hdi_wide.dropna(subset=[2020, 2022])

# Compute HDI change
hdi_wide["HDI_change_2020_2022"] = hdi_wide[2022] - hdi_wide[2020]

display(hdi_wide.head(10))

#Which countries show the greatest improvement in HDI from 2020 to 2022?
# Find the maximum improvement
max_improvement = hdi_wide["HDI_change_2020_2022"].max()

print("Maximum HDI improvement (2020 → 2022):", max_improvement)

# Countries with the greatest improvement
greatest_improvers = hdi_wide[
    hdi_wide["HDI_change_2020_2022"] == max_improvement
]

display(greatest_improvers[[2020, 2022, "HDI_change_2020_2022"]])

#Did any countries experience a decline in HDI? Provide possible reasons.
# Identify countries with HDI decline (2020 → 2022)
decline_countries = hdi_wide[hdi_wide["HDI_change_2020_2022"] < 0]

print("Countries that experienced a decline in HDI (2020 → 2022):")

if decline_countries.empty:
    print("No countries experienced a decline in HDI between 2020 and 2022.")
else:
    display(
        decline_countries
        .sort_values("HDI_change_2020_2022")
        [[2020, 2022, "HDI_change_2020_2022"]]
    )

#Which region has the highest and lowest average HDI across these three years?
south_asia = [
    "Afghanistan", "Bangladesh", "Bhutan", "India",
    "Maldives", "Nepal", "Pakistan", "Sri Lanka"
]

middle_east = [
    "Bahrain", "Iran", "Iraq", "Israel", "Jordan", "Kuwait",
    "Lebanon", "Oman", "Palestine", "Qatar", "Saudi Arabia",
    "Syria", "United Arab Emirates", "Yemen"
]

# Adding region column
hdi_problem1B_df["region"] = hdi_problem1B_df["country"].apply(
    lambda x: "South Asia" if x in south_asia
    else "Middle East" if x in middle_east
    else None
)

#Compute average HDI by region (2020–2022)
region_avg = (
    hdi_problem1B_df
    .dropna(subset=["region"])
    .groupby("region")["hdi"]
    .mean()
    .sort_values(ascending=False)
)

print("Average HDI by region (2020–2022):")
display(region_avg)

"""Discuss how global events (e.g., the COVID-19 pandemic) may have affected HDI trends during
this period.

Global events like the COVID-19 pandemic significantly affected HDI trends between 2020 and 2022. In 2020 and 2021, many countries saw slow growth or declines in HDI because of higher death rates, economic slowdown, job losses, and interruptions in education and healthcare systems. The slight improvement in 2022 indicates gradual economic recovery, better healthcare management, and government policies supporting social and economic development.

#Problem 2 – Advanced HDI Exploration (South Asia)
"""

# -----------------------------
# Task 1: Create South Asia Subset
# -----------------------------

south_asia = [
    'Afghanistan','Bangladesh','Bhutan','India',
    'Maldives','Nepal','Pakistan','Sri Lanka'
]

sa_df = df[df['country'].isin(south_asia)].copy()

# Replace special missing symbol
sa_df.replace("–", np.nan, inplace=True)

# Convert required numeric columns
for col in ['hdi', 'life expectancy', 'gross inc percap', 'gender development']:
    if col in sa_df.columns:
        sa_df[col] = pd.to_numeric(sa_df[col], errors='coerce')

# Drop rows with missing HDI
sa_df.dropna(subset=['hdi'], inplace=True)

# -----------------------------
# SHOW OUTPUT (THIS WAS MISSING)
# -----------------------------
print("South Asia dataset preview:")
display(sa_df.head())

print("\nDataset shape:", sa_df.shape)

# Save South Asia dataset
sa_df.to_csv("HDI_SouthAsia.csv", index=False)

# -----------------------------
# Task 2: Composite Development Score
# -----------------------------
# Work on a copy to avoid modifying original dataframe
south_asia = hdi_south_asia_df.copy()

# Min–max normalization for Life Expectancy
south_asia["life_expectancy_index"] = (
    (south_asia["life_expectancy"] - south_asia["life_expectancy"].min()) /
    (south_asia["life_expectancy"].max() - south_asia["life_expectancy"].min())
)

# Min–max normalization for GNI per Capita
south_asia["gni_index"] = (
    (south_asia["gross_inc_percap"] - south_asia["gross_inc_percap"].min()) /
    (south_asia["gross_inc_percap"].max() - south_asia["gross_inc_percap"].min())
)

# Compute Composite Development Score
south_asia["Composite_Score"] = (
    0.30 * south_asia["life_expectancy_index"] +
    0.30 * south_asia["gni_index"]
)

display(south_asia[[
    "country",
    "life_expectancy",
    "gross_inc_percap",
    "Composite_Score"
]].head(10))

# Rank countries
composite_rank = (
    south_asia
    .sort_values("Composite_Score", ascending=False)
    [["country", "Composite_Score", "hdi"]]
)

display(composite_rank)

# Plot Top 5 countries
# Use 2022 data only to avoid duplicate country entries
south_asia_2022 = south_asia[south_asia["year"] == 2022].copy()

# Rank countries by Composite Score
composite_rank = (
    south_asia_2022
    .sort_values("Composite_Score", ascending=False)
    [["country", "Composite_Score", "hdi"]]
)

display(composite_rank)

# Plot top 5 countries
top5_composite = composite_rank.head(5)

plt.figure(figsize=(8, 4))
plt.barh(
    top5_composite["country"],
    top5_composite["Composite_Score"]
)
plt.xlabel("Composite Development Score")
plt.title("Top 5 South Asian Countries by Composite Development Score (2022)")
plt.gca().invert_yaxis()
plt.grid(axis="x", alpha=0.3)
plt.show()

# -----------------------------
# Outlier detection using IQR method
#Task 3
# -----------------------------

def iqr_outlier_flags(data_col):
    q1 = data_col.quantile(0.25)
    q3 = data_col.quantile(0.75)
    iqr = q3 - q1
    min_val = q1 - 1.5 * iqr
    max_val = q3 + 1.5 * iqr
    return data_col.apply(lambda x: x < min_val or x > max_val)

# -----------------------------
# Apply outlier detection
# -----------------------------

south_asia = south_asia.copy()

south_asia["HDI_outlier"] = iqr_outlier_flags(south_asia["hdi"])
south_asia["GNI_outlier"] = iqr_outlier_flags(south_asia["gross_inc_percap"])

# Final outlier flag
south_asia["Outlier"] = south_asia[["HDI_outlier", "GNI_outlier"]].any(axis=1)

# -----------------------------
# Display results
# -----------------------------

print("Identified outlier countries:")
display(
    south_asia.loc[south_asia["Outlier"],
    ["country", "hdi", "gross_inc_percap", "HDI_outlier", "GNI_outlier"]]
)

"""SCATTER PLOT"""

import matplotlib.pyplot as plt

# -----------------------------
# Outlier Visualization: HDI vs GNI
# -----------------------------

plt.figure(figsize=(8, 5))

# Separate data for clarity
non_outliers = south_asia.loc[~south_asia["Outlier"]]
outliers = south_asia.loc[south_asia["Outlier"]]

# Plot non-outliers
plt.scatter(
    non_outliers["gross_inc_percap"],
    non_outliers["hdi"],
    c='skyblue',
    edgecolor='k',
    alpha=0.6,
    label='Non-outliers'
)

# Plot outliers
plt.scatter(
    outliers["gross_inc_percap"],
    outliers["hdi"],
    c='tomato',
    edgecolor='k',
    alpha=0.8,
    label='Outliers'
)

# Labels and title
plt.xlabel("GNI per Capita")
plt.ylabel("HDI")
plt.title("Outlier Detection: GNI per Capita vs HDI (South Asia)")
plt.legend()
plt.grid(linestyle='--', alpha=0.3)
plt.tight_layout()
plt.show()

# -----------------------------
# Task 4: Metric Relationships
# -----------------------------
# Keep only relevant columns and remove rows with NaN
cols_to_use = ["hdi", "gender_development", "life_expectancy"]
metrics = south_asia[cols_to_use].copy().dropna()

# Compute correlations with HDI
corr_results = {}
for col in ["gender_development", "life_expectancy"]:
    corr_results[col] = metrics["hdi"].corr(metrics[col])

# Display results
print("Pearson Correlation of HDI with other metrics:")
for key, val in corr_results.items():
    print(f"{key.replace('_',' ').title()} vs HDI: {val:.3f}")

"""Scatter plot: HDI vs Gender Development Index"""

import matplotlib.pyplot as plt
import numpy as np

# Scatter plot: HDI vs Gender Development Index
plt.figure(figsize=(7,5))
plt.scatter(metrics["gender_development"], metrics["hdi"], color='skyblue', alpha=0.7)

# Linear trendline
slope, intercept = np.polyfit(metrics["gender_development"], metrics["hdi"], 1)
plt.plot(
    metrics["gender_development"],
    slope * metrics["gender_development"] + intercept,
    color='red',
    linewidth=2
)

# Labels and title
plt.xlabel("Gender Development Index")
plt.ylabel("HDI")
plt.title("HDI vs Gender Development Index (South Asia)")
plt.grid(True, alpha=0.3)
plt.show()

"""Scatter plot: HDI vs Life Expectancy"""

import matplotlib.pyplot as plt
import numpy as np

# Scatter plot: HDI vs Life Expectancy
plt.figure(figsize=(7,5))
plt.scatter(metrics["life_expectancy"], metrics["hdi"], color='lightgreen', alpha=0.7)

# Linear trendline
slope, intercept = np.polyfit(metrics["life_expectancy"], metrics["hdi"], 1)
plt.plot(
    metrics["life_expectancy"],
    slope * metrics["life_expectancy"] + intercept,
    color='red',
    linewidth=2
)

# Labels and title
plt.xlabel("Life Expectancy")
plt.ylabel("HDI")
plt.title("HDI vs Life Expectancy (South Asia)")
plt.grid(True, alpha=0.3)
plt.show()

"""Task 5: GNI vs HDI Gap Analysis (2022)"""

#Task 5- Gap Analysis
import matplotlib.pyplot as plt


# Define South Asia countries
sa_countries = [
    "Afghanistan", "Bangladesh", "Bhutan", "India",
    "Maldives", "Nepal", "Pakistan", "Sri Lanka"
]

# Subset for 2022
sa_data_2022 = df[(df["country"].isin(sa_countries)) & (df["year"] == 2022)].copy()

# Check if required columns exist
required_cols = ["gross_inc_percap", "hdi"]
if all(col in sa_data_2022.columns for col in required_cols):

    # Compute GNI–HDI gap
    sa_data_2022["GNI_HDI_Gap"] = sa_data_2022["gross_inc_percap"] - sa_data_2022["hdi"]

    # Rank countries by gap
    top_positive = sa_data_2022.nlargest(8, "GNI_HDI_Gap")[["country", "GNI_HDI_Gap", "gross_inc_percap", "hdi"]]
    top_negative = sa_data_2022.nsmallest(8, "GNI_HDI_Gap")[["country", "GNI_HDI_Gap", "gross_inc_percap", "hdi"]]

    # Display results
    print("\nTop positive GNI–HDI gaps:")
    display(top_positive)

    print("\nTop negative GNI–HDI gaps:")
    display(top_negative)

    # Plot top 3 positive gaps
    plt.figure(figsize=(6,4))
    top_pos_plot = top_positive.head(3).sort_values("GNI_HDI_Gap")
    plt.barh(top_pos_plot["country"], top_pos_plot["GNI_HDI_Gap"], color='skyblue', edgecolor='k')
    plt.title("Top 3 Positive GNI–HDI Gaps (South Asia, 2022)")
    plt.xlabel("GNI–HDI Gap")
    plt.ylabel("Country")
    plt.tight_layout()
    plt.show()

    # Plot top 3 negative gaps
    plt.figure(figsize=(6,4))
    top_neg_plot = top_negative.head(3).sort_values("GNI_HDI_Gap")
    plt.barh(top_neg_plot["country"], top_neg_plot["GNI_HDI_Gap"], color='salmon', edgecolor='k')
    plt.title("Top 3 Negative GNI–HDI Gaps (South Asia, 2022)")
    plt.xlabel("GNI–HDI Gap")
    plt.ylabel("Country")
    plt.tight_layout()
    plt.show()

else:
    print("\nRequired columns for GNI–HDI gap analysis are missing.")

"""Discuss the implications of the gap, e.g., cases where GNI is high but HDI
is lower than expected.

The GNI–HDI gap shows the difference between a country’s income and its actual human development results.
A positive gap means a country has relatively high income, but this wealth has not fully improved health, education, or overall well-being. This could happen due to unequal income distribution, low public investment in social sectors, or structural development challenges.
A negative gap indicates that some countries achieve better human development outcomes even with lower income, suggesting more efficient social policies and effective use of resources.

#Problem 3 – Task 1: Regional Subset Creation
"""

# -----------------------------
# Task 1: Create Regional Subsets
# -----------------------------
# Regional subsets
south_asia = ['Afghanistan','Bangladesh','Bhutan','India','Maldives','Nepal','Pakistan','Sri Lanka']
middle_east = ['Bahrain','Iran','Iraq','Israel','Jordan','Kuwait','Lebanon','Oman','Palestine','Qatar','Saudi Arabia','Syria','United Arab Emirates','Yemen']

sa_3 = hdi_1b[hdi_1b['country'].isin(south_asia)]
me_3 = hdi_1b[hdi_1b['country'].isin(middle_east)]

# Save CSVs
sa_3.to_csv("HDI_SouthAsia_2020_2022.csv", index=False)
me_3.to_csv("HDI_MiddleEast_2020_2022.csv", index=False)

# Quick preview
display(sa_3.head())
display(me_3.head())

# -----------------------------
# Task 2: Descriptive Statistics
# -----------------------------
sa_mean = sa_3['hdi'].mean()
sa_std = sa_3['hdi'].std()


me_mean = me_3['hdi'].mean()
me_std = me_3['hdi'].std()


print("South Asia – Mean HDI:", sa_mean)
print("South Asia – Std HDI:", sa_std)
print("Middle East – Mean HDI:", me_mean)
print("Middle East – Std HDI:", me_std)

# -----------------------------
# Task 3: Top & Bottom Performers
# -----------------------------
sa_top3 = sa_3.sort_values(by='hdi', ascending=False).head(3)
sa_bottom3 = sa_3.sort_values(by='hdi').head(3)


me_top3 = me_3.sort_values(by='hdi', ascending=False).head(3)
me_bottom3 = me_3.sort_values(by='hdi').head(3)


performers_df = pd.concat([sa_top3, sa_bottom3, me_top3, me_bottom3])


plt.figure(figsize=(9,5))
sns.barplot(data=performers_df, x='country', y='hdi')
plt.title("Top & Bottom HDI Performers: South Asia vs Middle East")
plt.xlabel("Country")
plt.ylabel("HDI")
plt.xticks(rotation=45)
plt.show()

# -----------------------------
# Task 4: Metric Comparisons
# -----------------------------
#  Add region column if missing
if "region" not in hdi_southasia_2020_2022.columns:
    hdi_southasia_2020_2022 = hdi_southasia_2020_2022.copy()
    hdi_southasia_2020_2022["region"] = "South Asia"

if "region" not in hdi_middleeast_2020_2022.columns:
    hdi_middleeast_2020_2022 = hdi_middleeast_2020_2022.copy()
    hdi_middleeast_2020_2022["region"] = "Middle East"

#  Combine both regions into one dataframe
hdi_regions = pd.concat([hdi_southasia_2020_2022, hdi_middleeast_2020_2022], ignore_index=True)

# Now group
gdi_avg = (
    hdi_regions
    .groupby(["region", "year"])["gender_development"]
    .mean()
    .reset_index()
)

display(gdi_avg)
gdi_pivot = gdi_avg.pivot(index="year", columns="region", values="gender_development")
display(gdi_pivot)

ax = gdi_pivot.plot(
    kind='bar',
    figsize=(7,4),
    color=['skyblue','salmon'],
    edgecolor='k'
)

# Titles and labels
ax.set_title("Gender Development Index: South Asia vs Middle East (2020–2022)")
ax.set_xlabel("Year")
ax.set_ylabel("Average Gender Development Index")

# Grid and ticks
ax.grid(axis='y', linestyle='--', alpha=0.3)
ax.set_xticklabels(ax.get_xticklabels(), rotation=0)

# Legend outside plot
ax.legend(title="Region", bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

#– Life Expectancy Index {"life expectancy"}
le_avg = (
    hdi_regions
    .groupby(["region", "year"])["life_expectancy"]
    .mean()
    .reset_index()
)

display(le_avg)

le_pivot = le_avg.pivot(index="year", columns="region", values="life_expectancy")
display(le_pivot)

#Plot grouped bar chart(life_expentency)
ax = le_pivot.plot(
    kind='bar',
    figsize=(7,4),
    color=['lightgreen','orange'],
    edgecolor='k'
)

# Titles and labels
ax.set_title("Life Expectancy: South Asia vs Middle East (2020–2022)")
ax.set_xlabel("Year")
ax.set_ylabel("Average Life Expectancy")

# Grid and ticks
ax.grid(axis='y', linestyle='--', alpha=0.3)
ax.set_xticklabels(ax.get_xticklabels(), rotation=0)

# Legend outside
ax.legend(title="Region", bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

#– GNI per Capita Index {"gross inc percap"}
#Group
gni_avg = (
    hdi_regions
    .groupby(["region", "year"])["gross_inc_percap"]
    .mean()
    .reset_index()
)

display(gni_avg)

#Pivot
gni_pivot = gni_avg.pivot(index="year", columns="region", values="gross_inc_percap")
display(gni_pivot)

#Plot grouped bar chart(gross inc percap)
ax = gni_pivot.plot(
    kind='bar',
    figsize=(7,4),
    color=['skyblue','salmon'],
    edgecolor='k'
)

# Titles and labels
ax.set_title("GNI per Capita: South Asia vs Middle East (2020–2022)")
ax.set_xlabel("Year")
ax.set_ylabel("Average GNI per Capita")

# Grid and ticks
ax.grid(axis='y', linestyle='--', alpha=0.3)
ax.set_xticklabels(ax.get_xticklabels(), rotation=0)

# Legend outside
ax.legend(title="Region", bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

"""Compute HDI range (max - min) for each region"""

#Task 5
# Compute HDI range (max - min) for each region
hdi_range = (
    hdi_regions
    .groupby("region")["hdi"]
    .agg(["max", "min"])
)

hdi_range["HDI_Range"] = hdi_range["max"] - hdi_range["min"]

display(hdi_range[["HDI_Range"]])

"""Compute coefficient of variation (CV) for HDI by region"""

# Compute coefficient of variation (CV) for HDI by region
hdi_cv = (
    hdi_regions
    .groupby("region")["hdi"]
    .agg(["mean", "std"])
)

hdi_cv["CV"] = hdi_cv["std"] / hdi_cv["mean"]

display(hdi_cv[["CV"]])

#Task 6: Correlation Analysis
# -----------------------------
# HDI vs Gender Development Index: Correlation by Region
# -----------------------------

# South Asia
sa_metrics = hdi_southasia_2020_2022[["hdi", "gender_development"]].dropna()
sa_corr = sa_metrics["hdi"].corr(sa_metrics["gender_development"])

# Middle East
me_metrics = hdi_middleeast_2020_2022[["hdi", "gender_development"]].dropna()
me_corr = me_metrics["hdi"].corr(me_metrics["gender_development"])

# Display results
print("Pearson Correlation between HDI and Gender Development Index:")
print(f" - South Asia: {sa_corr:.3f}")
print(f" - Middle East: {me_corr:.3f}")

# -----------------------------
# HDI vs Life Expectancy: Correlation by Region
# -----------------------------

# South Asia
sa_metrics = hdi_southasia_2020_2022[["hdi", "life_expectancy"]].dropna()
sa_le_corr = sa_metrics["hdi"].corr(sa_metrics["life_expectancy"])

# Middle East
me_metrics = hdi_middleeast_2020_2022[["hdi", "life_expectancy"]].dropna()
me_le_corr = me_metrics["hdi"].corr(me_metrics["life_expectancy"])

# Display results
print("Pearson Correlation between HDI and Life Expectancy:")
print(f" - South Asia: {sa_le_corr:.3f}")
print(f" - Middle East: {me_le_corr:.3f}")

#scatter plots with trendlines for each correlation.
#SOUTH ASIA
import matplotlib.pyplot as plt
import numpy as np

# -----------------------------
# Scatter plot: HDI vs Gender Development Index (South Asia)
# -----------------------------

sa_metrics = hdi_southasia_2020_2022[["hdi","gender_development"]].dropna()

plt.figure(figsize=(5,4))

# Scatter points
plt.scatter(sa_metrics["gender_development"], sa_metrics["hdi"], color='skyblue', alpha=0.7, edgecolor='k')

# Linear trendline
slope, intercept = np.polyfit(sa_metrics["gender_development"], sa_metrics["hdi"], 1)
x_vals = np.linspace(sa_metrics["gender_development"].min(), sa_metrics["gender_development"].max(), 100)
plt.plot(x_vals, slope*x_vals + intercept, color='red', linewidth=2)

# Labels, title, grid
plt.xlabel("Gender Development Index")
plt.ylabel("HDI")
plt.title("HDI vs Gender Development Index (South Asia)")
plt.grid(alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

#MIDDLE EAST
import matplotlib.pyplot as plt
import numpy as np

# -----------------------------
# Scatter plot: HDI vs Gender Development Index (Middle East)
# -----------------------------

me_metrics = hdi_middleeast_2020_2022[["hdi","gender_development"]].dropna()

plt.figure(figsize=(5,4))

# Scatter points
plt.scatter(me_metrics["gender_development"], me_metrics["hdi"], color='salmon', alpha=0.7, edgecolor='k')

# Linear trendline
slope, intercept = np.polyfit(me_metrics["gender_development"], me_metrics["hdi"], 1)
x_vals = np.linspace(me_metrics["gender_development"].min(), me_metrics["gender_development"].max(), 100)
plt.plot(x_vals, slope*x_vals + intercept, color='darkred', linewidth=2)

# Labels, title, grid
plt.xlabel("Gender Development Index")
plt.ylabel("HDI")
plt.title("HDI vs Gender Development Index (Middle East)")
plt.grid(alpha=0.3, linestyle='--')
plt.tight_layout()
plt.show()

"""HDI vs Life Expectancy"""

#SOUTH ASIA
plt.figure(figsize=(5,4))
plt.scatter(
    hdi_southasia_2020_2022["life_expectancy"],
    hdi_southasia_2020_2022["hdi"],
    alpha=0.7
)

# Trendline
m, b = np.polyfit(
    hdi_southasia_2020_2022["life_expectancy"],
    hdi_southasia_2020_2022["hdi"],
    1
)
x = np.linspace(
    hdi_southasia_2020_2022["life_expectancy"].min(),
    hdi_southasia_2020_2022["life_expectancy"].max(),
    100
)
plt.plot(x, m*x + b)

plt.xlabel("Life Expectancy")
plt.ylabel("HDI")
plt.title("HDI vs Life Expectancy (South Asia)")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

#MIDDLE EAST
plt.figure(figsize=(5,4))
plt.scatter(
    hdi_middleeast_2020_2022["life_expectancy"],
    hdi_middleeast_2020_2022["hdi"],
    alpha=0.7
)

# Trendline
m, b = np.polyfit(
    hdi_middleeast_2020_2022["life_expectancy"],
    hdi_middleeast_2020_2022["hdi"],
    1
)
x = np.linspace(
    hdi_middleeast_2020_2022["life_expectancy"].min(),
    hdi_middleeast_2020_2022["life_expectancy"].max(),
    100
)
plt.plot(x, m*x + b)

plt.xlabel("Life Expectancy")
plt.ylabel("HDI")
plt.title("HDI vs Life Expectancy (Middle East)")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

#Task 7: Outlier Detection
#Outlier Detection Function
# Function to detect outliers using 1.5 × IQR rule
def detect_outliers_iqr(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return series[(series < lower_bound) | (series > upper_bound)]

#South Asia Outliers
# South Asia HDI outliers
sa_hdi_outliers = detect_outliers_iqr(
    hdi_southasia_2020_2022["hdi"]
)

# South Asia GNI per Capita outliers
sa_gni_outliers = detect_outliers_iqr(
    hdi_southasia_2020_2022["gross_inc_percap"]
)

print("South Asia HDI Outliers:")
display(hdi_southasia_2020_2022.loc[sa_hdi_outliers.index, ["country", "year", "hdi"]])

print("South Asia GNI per Capita Outliers:")
display(hdi_southasia_2020_2022.loc[sa_gni_outliers.index, ["country", "year", "gross_inc_percap"]])

#Middle East Outliers
# Middle East HDI outliers
me_hdi_outliers = detect_outliers_iqr(
    hdi_middleeast_2020_2022["hdi"]
)

# Middle East GNI per Capita outliers
me_gni_outliers = detect_outliers_iqr(
    hdi_middleeast_2020_2022["gross_inc_percap"]
)

print("Middle East HDI Outliers:")
display(hdi_middleeast_2020_2022.loc[me_hdi_outliers.index, ["country", "year", "hdi"]])

print("Middle East GNI per Capita Outliers:")
display(hdi_middleeast_2020_2022.loc[me_gni_outliers.index, ["country", "year", "gross_inc_percap"]])

#South Asia scatter plot with outliers
#function define
def iqr_bounds(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    return Q1 - 1.5 * IQR, Q3 + 1.5 * IQR

sa = hdi_southasia_2020_2022.copy()

# Compute IQR bounds
hdi_lb, hdi_ub = iqr_bounds(sa["hdi"])
gni_lb, gni_ub = iqr_bounds(sa["gross_inc_percap"])

# Identify outliers
sa["Outlier"] = (
    (sa["hdi"] < hdi_lb) | (sa["hdi"] > hdi_ub) |
    (sa["gross_inc_percap"] < gni_lb) | (sa["gross_inc_percap"] > gni_ub)
)

plt.figure(figsize=(6,4))
plt.scatter(
    sa.loc[~sa["Outlier"], "gross_inc_percap"],
    sa.loc[~sa["Outlier"], "hdi"],
    label="Non-outliers",
    alpha=0.7
)
plt.scatter(
    sa.loc[sa["Outlier"], "gross_inc_percap"],
    sa.loc[sa["Outlier"], "hdi"],
    label="Outliers",
    alpha=0.9
)

plt.xlabel("GNI per Capita")
plt.ylabel("HDI")
plt.title("South Asia: HDI vs GNI per Capita (Outliers Highlighted)")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

#Middle East scatter plot with outliers
me = hdi_middleeast_2020_2022.copy()

# Compute IQR bounds
hdi_lb, hdi_ub = iqr_bounds(me["hdi"])
gni_lb, gni_ub = iqr_bounds(me["gross_inc_percap"])

# Identify outliers
me["Outlier"] = (
    (me["hdi"] < hdi_lb) | (me["hdi"] > hdi_ub) |
    (me["gross_inc_percap"] < gni_lb) | (me["gross_inc_percap"] > gni_ub)
)

plt.figure(figsize=(6,4))
plt.scatter(
    me.loc[~me["Outlier"], "gross_inc_percap"],
    me.loc[~me["Outlier"], "hdi"],
    label="Non-outliers",
    alpha=0.7
)
plt.scatter(
    me.loc[me["Outlier"], "gross_inc_percap"],
    me.loc[me["Outlier"], "hdi"],
    label="Outliers",
    alpha=0.9
)

plt.xlabel("GNI per Capita")
plt.ylabel("HDI")
plt.title("Middle East: HDI vs GNI per Capita (Outliers Highlighted)")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

