# -*- coding: utf-8 -*-
"""FinalAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKqEGcQE8MJEpBE-87tYfXqVd3sgBsJ4

### HDI Assignment I - Statistical Interpretation & EDA
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("Human_Development_Index_Dataset.csv", encoding="latin-1")
df.head()

"""## PROBLEM 1A – Single Year HDI (2022)

1A.1 Extract Latest Year (2022)


"""

hdi_2022_df = df[df["year"] == 2022].copy()

"""1A.2 Basic Data Exploration"""

hdi_2022_df.head(10)
hdi_2022_df.shape
hdi_2022_df.info()

"""1A.3 Missing Values & Cleaning"""

hdi_2022_df.isnull().sum()

# Convert important numeric columns
hdi_2022_df["hdi"] = pd.to_numeric(hdi_2022_df["hdi"], errors="coerce")
hdi_2022_df["gross_inc_percap"] = pd.to_numeric(hdi_2022_df["gross_inc_percap"], errors="coerce")

# Remove duplicates
hdi_2022_df = hdi_2022_df.drop_duplicates()

# Drop rows with critical missing values
hdi_2022_df = hdi_2022_df.dropna(subset=["country", "hdi"])

"""Report Justification:
Rows with missing HDI and country values were removed because these fields are essential for ranking and comparison. Numeric columns were converted to ensure consistency.

1A.4 Basic Statistics
"""

mean_hdi = hdi_2022_df["hdi"].mean()
median_hdi = hdi_2022_df["hdi"].median()
std_hdi = hdi_2022_df["hdi"].std()

highest = hdi_2022_df.loc[hdi_2022_df["hdi"].idxmax(), ["country","hdi"]]
lowest = hdi_2022_df.loc[hdi_2022_df["hdi"].idxmin(), ["country","hdi"]]

mean_hdi, median_hdi, std_hdi, highest, lowest

"""1A.5 Filter HDI > 0.800 & Sort by GNI"""

high_hdi = hdi_2022_df[hdi_2022_df["hdi"] > 0.800]
top10 = high_hdi.sort_values(by="gross_inc_percap", ascending=False).head(10)
top10

"""1A.6 Add HDI Category"""

def hdi_category(val):
    if val < 0.550:
        return "Low"
    elif val <= 0.699:
        return "Medium"
    elif val <= 0.799:
        return "High"
    else:
        return "Very High"

hdi_2022_df["HDI_Category"] = hdi_2022_df["hdi"].apply(hdi_category)

hdi_2022_df["HDI_Category"].value_counts()

# Save for submission
hdi_2022_df.to_csv("HDI_category_added.csv", index=False)

"""## **PROBLEM 1B – HDI Trends (2020–2022**)

1B.1 Filter Years & Save
"""

hdi_1b = df[df["year"].isin([2020, 2021, 2022])].copy()

hdi_1b["hdi"] = pd.to_numeric(hdi_1b["hdi"], errors="coerce")
hdi_1b["gross_inc_percap"] = pd.to_numeric(hdi_1b["gross_inc_percap"], errors="coerce")

hdi_1b = hdi_1b.dropna(subset=["country","year","hdi"])

hdi_1b.to_csv("HDI_problem1B.csv", index=False)

"""1B.2 Line Chart – HDI Trend (5 Countries)"""

countries = ["Nepal","India","Bangladesh","Pakistan","Sri Lanka"]
line_df = hdi_1b[hdi_1b["country"].isin(countries)]

plt.figure(figsize=(10,6))
sns.lineplot(data=line_df, x="year", y="hdi", hue="country", marker="o")
plt.title("HDI Trend of Selected Countries (2020–2022)")
plt.xlabel("Year")
plt.ylabel("HDI")
plt.show()

"""1B.3 Bar Chart – Average HDI by Region"""

region_map = {
    "Afghanistan":"South Asia","Bangladesh":"South Asia","Bhutan":"South Asia",
    "India":"South Asia","Maldives":"South Asia","Nepal":"South Asia",
    "Pakistan":"South Asia","Sri Lanka":"South Asia",

    "Bahrain":"Middle East","Iran":"Middle East","Iraq":"Middle East",
    "Israel":"Middle East","Jordan":"Middle East","Kuwait":"Middle East",
    "Lebanon":"Middle East","Oman":"Middle East","Palestine":"Middle East",
    "Qatar":"Middle East","Saudi Arabia":"Middle East","Syria":"Middle East",
    "United Arab Emirates":"Middle East","Yemen":"Middle East"
}

hdi_1b["region"] = hdi_1b["country"].map(region_map)
hdi_1b = hdi_1b.dropna(subset=["region"])

region_year_avg = hdi_1b.groupby(["region","year"])["hdi"].mean().reset_index()

plt.figure(figsize=(12,6))
sns.barplot(data=region_year_avg, x="region", y="hdi", hue="year")
plt.title("Average HDI by Region (2020–2022)")
plt.xlabel("Region")
plt.ylabel("Average HDI")
plt.show()

"""Report Justification:
Since the dataset did not include a region column, regions were manually assigned using a country–region mapping based on UN classifications.

1B.4 Box Plot – HDI Distribution
"""

plt.figure(figsize=(8,5))
sns.boxplot(data=hdi_1b, x="year", y="hdi")
plt.title("HDI Distribution for 2020, 2021, and 2022")
plt.xlabel("Year")
plt.ylabel("HDI")
plt.show()

"""The median HDI shows gradual improvement from 2020 to 2022. The wider spread in 2020 reflects greater inequality, likely due to COVID-19 impacts.

1B.5 Scatter Plot – HDI vs GNI
"""

plt.figure(figsize=(8,6))
sns.scatterplot(data=hdi_1b, x="gross_inc_percap", y="hdi")
plt.title("HDI vs GNI per Capita (2020–2022)")
plt.xlabel("GNI per Capita")
plt.ylabel("HDI")
plt.show()

"""## PROBLEM 2 – Advanced HDI Exploration
## (South Asia Focus)

Problem 2.1: South Asia Subset
"""

south_asia = [
    "Afghanistan","Bangladesh","Bhutan","India",
    "Maldives","Nepal","Pakistan","Sri Lanka"
]

hdi_sa = df[df["country"].isin(south_asia)].copy()

# Convert numeric columns
hdi_sa["hdi"] = pd.to_numeric(hdi_sa["hdi"], errors="coerce")
hdi_sa["gross_inc_percap"] = pd.to_numeric(hdi_sa["gross_inc_percap"], errors="coerce")
hdi_sa["life_expectancy"] = pd.to_numeric(hdi_sa["life_expectancy"], errors="coerce")

hdi_sa = hdi_sa.dropna(subset=["country","hdi"])

# Save file
hdi_sa.to_csv("HDI_SouthAsia.csv", index=False)
hdi_sa.head()

"""Problem 2.2: Composite Development Score

Formula (as given):
Composite Score = 0.30 × Life Expectancy + 0.30 × GNI per Capita
"""

hdi_sa["Composite_Score"] = (
    0.30 * hdi_sa["life_expectancy"] +
    0.30 * hdi_sa["gross_inc_percap"]
)

# Ranking
composite_rank = hdi_sa.sort_values(by="Composite_Score", ascending=False)
composite_rank[["country","Composite_Score","hdi"]]

"""Report Line:
Maldives and Sri Lanka rank highest by Composite Score, while Afghanistan ranks lowest due to weak income and health indicators. Composite Score ranking broadly aligns with HDI ranking, with minor differences.

Top 5 Horizontal Bar Chart
"""

top5_comp = composite_rank.head(5)

plt.figure(figsize=(8,5))
sns.barplot(data=top5_comp, x="Composite_Score", y="country")
plt.title("Top 5 South Asian Countries by Composite Score")
plt.xlabel("Composite Score")
plt.ylabel("Country")
plt.show()

"""Problem 2.3: Outlier Detection (1.5 × IQR Rule)"""

Q1 = hdi_sa["hdi"].quantile(0.25)
Q3 = hdi_sa["hdi"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers_sa = hdi_sa[(hdi_sa["hdi"] < lower) | (hdi_sa["hdi"] > upper)]
outliers_sa[["country","hdi","gross_inc_percap"]]

"""Afghanistan appears as a low-HDI outlier, while Maldives shows higher HDI relative to the region due to strong tourism-driven income."""

#Scatter Plot with Outliers Highlighted
plt.figure(figsize=(8,6))
sns.scatterplot(data=hdi_sa, x="gross_inc_percap", y="hdi", label="Normal")
sns.scatterplot(data=outliers_sa, x="gross_inc_percap", y="hdi",
                color="red", label="Outliers")
plt.title("Outliers in South Asia: HDI vs GNI per Capita")
plt.xlabel("GNI per Capita")
plt.ylabel("HDI")
plt.legend()
plt.show()

"""Problem 2.4: Metric Relationships (Correlation)

"""

corr_life = hdi_sa["hdi"].corr(hdi_sa["life_expectancy"])
corr_gender = hdi_sa["hdi"].corr(hdi_sa["gender_development"])

corr_life, corr_gender

#Scatter + Trendline
sns.lmplot(data=hdi_sa, x="life_expectancy", y="hdi")
plt.title("HDI vs Life Expectancy")

sns.lmplot(data=hdi_sa, x="gender_development", y="hdi")
plt.title("HDI vs Gender Development")

"""Conclusion:

Life Expectancy shows the strongest correlation with HDI, while Gender Development shows a comparatively weaker relationship.

Problem 2.5: GNI–HDI Gap Analysis
"""

hdi_sa["GNI_HDI_Gap"] = hdi_sa["gross_inc_percap"] - hdi_sa["hdi"]

gap_sorted = hdi_sa.sort_values(by="GNI_HDI_Gap", ascending=False)

top_positive = gap_sorted.head(3)
top_negative = gap_sorted.tail(3)

top_positive, top_negative

#Bar Charts
plt.figure(figsize=(6,4))
sns.barplot(data=top_positive, x="country", y="GNI_HDI_Gap")
plt.title("Top 3 Positive GNI–HDI Gaps")
plt.show()

plt.figure(figsize=(6,4))
sns.barplot(data=top_negative, x="country", y="GNI_HDI_Gap")
plt.title("Top 3 Negative GNI–HDI Gaps")
plt.show()

"""A positive gap indicates income not translating effectively into human development, while a negative gap suggests strong social outcomes despite low income.

## PROBLEM 3 – South Asia vs Middle East

Problem 3.1: Create Regional Subsets
"""

middle_east = [
    "Bahrain","Iran","Iraq","Israel","Jordan","Kuwait","Lebanon",
    "Oman","Palestine","Qatar","Saudi Arabia","Syria",
    "United Arab Emirates","Yemen"
]

sa_2020_22 = hdi_1b[hdi_1b["country"].isin(south_asia)]
me_2020_22 = hdi_1b[hdi_1b["country"].isin(middle_east)]

sa_2020_22.to_csv("HDI_SouthAsia_2020_2022.csv", index=False)
me_2020_22.to_csv("HDI_MiddleEast_2020_2022.csv", index=False)

"""Problem 3.2: Descriptive Statistics"""

sa_mean = sa_2020_22["hdi"].mean()
sa_std = sa_2020_22["hdi"].std()

me_mean = me_2020_22["hdi"].mean()
me_std = me_2020_22["hdi"].std()

sa_mean, sa_std, me_mean, me_std

"""Answer:

Middle East performs better on average HDI than South Asia.

Problem 3.3: Top & Bottom Performers
"""

top_sa = sa_2020_22.sort_values(by="hdi", ascending=False).head(3)
bottom_sa = sa_2020_22.sort_values(by="hdi").head(3)

top_me = me_2020_22.sort_values(by="hdi", ascending=False).head(3)
bottom_me = me_2020_22.sort_values(by="hdi").head(3)

top_sa, bottom_sa, top_me, bottom_me

"""Problem 3.4: Metric Comparisons"""

metrics = ["gender_development","life_expectancy","gross_inc_percap"]

for m in metrics:
    plt.figure(figsize=(7,4))
    sns.barplot(
        x=["South Asia","Middle East"],
        y=[sa_2020_22[m].mean(), me_2020_22[m].mean()]
    )
    plt.title(f"{m}: South Asia vs Middle East")
    plt.ylabel("Average Value")
    plt.show()

"""Finding:

GNI per Capita shows the largest disparity between the two regions.

Problem 3.5: HDI Disparity
"""

range_sa = sa_2020_22["hdi"].max() - sa_2020_22["hdi"].min()
range_me = me_2020_22["hdi"].max() - me_2020_22["hdi"].min()

cv_sa = sa_2020_22["hdi"].std() / sa_2020_22["hdi"].mean()
cv_me = me_2020_22["hdi"].std() / me_2020_22["hdi"].mean()

range_sa, range_me, cv_sa, cv_me

"""Conclusion:

South Asia exhibits greater HDI variation than the Middle East.

Problem 3.6 & 3.7: Correlation & Outliers
"""

sa_corr = sa_2020_22["hdi"].corr(sa_2020_22["life_expectancy"])
me_corr = me_2020_22["hdi"].corr(me_2020_22["life_expectancy"])

sa_corr, me_corr

"""Final Insight:

Life expectancy strongly influences HDI in both regions, though the relationship is stronger in the Middle East.
"""

